apiVersion: v1
kind: Secret
metadata:
  name: seatsync-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: OWE2NzY3ODEyNzQzNmQzOTZjMjYyNjJhNDcyYzVhMmM0ZTJjMzk1NDYyNWI2YTcwNzE3MjczNzQ3NTc2Nzc3OA==
